import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  trailingSlash: true,
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "cms.sweetleaves.co" },
    ],
  },
  async redirects() {
    return [
      { source: "/in-store-shopping/", destination: "/", permanent: true },
      { source: "/press/", destination: "/blog/", permanent: true },
      { source: "/author/sweetleavesadmin/", destination: "/", permanent: true },
      { source: "/cannabis-101/", destination: "/blog/", permanent: true },
      { source: "/cannabis-seeds/", destination: "/shop-now/", permanent: true },
      { source: "/cbd/", destination: "/shop-now/", permanent: true },
      { source: "/edina-mn/", destination: "/", permanent: true },
      { source: "/higher-education/", destination: "/blog/", permanent: true },
      { source: "/higher-love/", destination: "/blog/", permanent: true },
      { source: "/location/minneapolis/", destination: "/", permanent: false },
      { source: "/minh-le-studio/", destination: "/shop-now/", permanent: true },
      { source: "/minneapolis-mn/", destination: "/", permanent: false },
      { source: "/minnetonka-mn/", destination: "/", permanent: false },
      { source: "/premium-cannabis-dispensary-edina-mn/", destination: "/", permanent: true },
      { source: "/premium-cannabis-dispensary-minneapolis-mn/", destination: "/", permanent: false },
      { source: "/premium-cannabis-dispensary-minnetonka-mn/", destination: "/", permanent: false },
      { source: "/premium-cannabis-dispensary-st-louis-park-mn/", destination: "/", permanent: true },
      { source: "/premium-cannabis-dispensary-st-paul-mn/", destination: "/", permanent: true },
      { source: "/recreational-cannabis/", destination: "/shop-now/", permanent: true },
      { source: "/richfield-mn/", destination: "/", permanent: true },
      { source: "/session-goods/", destination: "/shop-now/", permanent: true },
      { source: "/st-louis-park-mn/", destination: "/", permanent: true },
      { source: "/st-paul-mn/", destination: "/", permanent: true },
      { source: "/birchs-on-the-lake/", destination: "/brands/birchs-on-the-lake/", permanent: true },
      { source: "/blncd/", destination: "/", permanent: true },
      { source: "/cann/", destination: "/", permanent: true },
      { source: "/clrty/", destination: "/", permanent: true },
      { source: "/dogwalkers/", destination: "/brands/dogwalkers/", permanent: true },
      { source: "/find-wunder/", destination: "/", permanent: true },
      { source: "/gigli/", destination: "/brands/gigli/", permanent: true },
      { source: "/good-green/", destination: "/brands/good-green/", permanent: true },
      { source: "/grasslandz/", destination: "/brands/grasslandz/", permanent: true },
      { source: "/lakeside-cannabis-co/", destination: "/brands/lakeside-cannabis-co/", permanent: true },
      { source: "/mary-jane/", destination: "/brands/mary-jane/", permanent: true },
      { source: "/nebula/", destination: "/brands/nebula/", permanent: true },
      { source: "/nowadays/", destination: "/brands/nowadays/", permanent: true },
      { source: "/oliphant-brewing/", destination: "/brands/oliphant-brewing/", permanent: true },
      { source: "/ongrok/", destination: "/", permanent: true },
      { source: "/raw/", destination: "/", permanent: true },
      { source: "/rythm/", destination: "/brands/rythm/", permanent: true },
      { source: "/studio-tbd/", destination: "/", permanent: true },
      { source: "/sweetleaves/", destination: "/brands/sweetleaves/", permanent: true },
      { source: "/wild-state-cider-birdie/", destination: "/brands/wild-state-cider-birdie/", permanent: true },
      { source: "/wyld/", destination: "/brands/wyld/", permanent: true },
      { source: "/cannabis-accessories/", destination: "/", permanent: true },
      { source: "/cannabis-beverages/", destination: "/products/cannabis-beverages/", permanent: true },
      { source: "/disposable-vapes-and-carts/", destination: "/products/disposable-vapes-and-carts/", permanent: true },
      { source: "/edibles/", destination: "/products/edibles/", permanent: true },
      { source: "/flower/", destination: "/products/flower/", permanent: true },
      { source: "/pre-rolls/", destination: "/products/pre-rolls/", permanent: true },
      { source: "/faq/", destination: "/faqs/", permanent: true },
      { source: "/shop/", destination: "/shop-now/", permanent: true },
    ];
  },
};

export default nextConfig;
