import type { CatalogEntry } from "./catalog";

export const brands: CatalogEntry[] = [
  {
    slug: "sweetleaves",
    name: "Sweetleaves",
    dutchieParams: { "dtche[path]": "brands/sweetleaves" },
    headline: "Sweetleaves",
    category: "sweetleaves",
    subheadline: "Premium In-House Cannabis Products from Sweetleaves",
    body: "<p>At Sweetleaves, we believe life is sweeter with cannabis and community, and that care and quality should be present in every edible we make. Our infused offerings are designed with intention, from CBD-forward options like Pink Lemonade, which supports relaxation and recovery after a long day or workout, to a rotating variety pack featuring Peach, Pineapple, and Passionfruit for a flavorful, hybrid sativa-dominant experience. Each option is crafted with full-spectrum THC to deliver consistent effects and a balanced, enjoyable experience.</p><p>Bright and tropical profiles like Pineapple, Peach, and Passionfruit offer uplifting, energizing effects that fit naturally into daytime plans, social settings, or creative sessions. These edibles are designed to enhance mood, spark creativity, and bring a light, carefree feeling that makes everyday moments more vivid and engaging, whether you are unwinding, connecting with others, or simply enjoying the flow of the day.</p>",
    metaDescription:
      "Shop Sweetleaves cannabis products for Minneapolis, MN. Contact us today for more info about our cannabis products!",
    metaTitle: "Sweetleaves Products | Sweetleaves",
  },
  {
    slug: "nowadays",
    name: "Nowadays",
    headline: "Nowadays",
    category: "nowadays",
    subheadline: "We're Here for You With Quality Cannabis Brands like Nowadays",
    body: "<p>As Minnesota's first high-end recreational cannabis dispensary, Sweetleaves offers a unique experience and premium cannabis products. We open up new horizons with inspiration and innovation. Whether for the beginner or connoisseur, our selection caters to expectations and elegance. Discover the perfect flavor, potency, and enjoyment of cannabis beverages by Nowadays.</p><p>Nowadays stands for \"at present.\" Their variation of drink blends is a delight straight up over ice or combined with a favorite beverage. Natural fruit flavors and a gentle onset of effects within fifteen minutes are the perfect alternative to alcohol and eliminate the hangover. For going out or staying in, relaxing or socializing, choose to maintain or build your buzz and celebrate living in the now!</p><p>Nowadays recipes such as Pucker Up, Bramble On, Colada Livin', Razzle Dazzle, Chilled Heat, and Wake Whenever refresh, uplift, and put a healthy spin on a tasty cocktail. Sweetleaves is excited to share Nowadays beverages, and our budtenders are here to help you navigate potency levels and dosing. Spend some time with us or let us accommodate your hectic schedule with online ordering, in-store pickup, or delivery. Sweetleaves is where your dreams become sweeter.</p>",
    metaDescription:
      "Shop Nowadays cannabis products for a premium experience. Explore our selection of high-quality products for ultimate relaxation.",
    metaTitle: "Nowadays Cannabis Products | Sweetleaves",
  },
  {
    slug: "gigli",
    name: "Gigli",
    headline: "Gigli",
    category: "gigli",
    subheadline: "Enjoy Ultra-High-Quality Cannabis from Sweetleaves",
    body: "<p>A visit to Sweetleaves is unlike any other shopping experience. We are the first upscale cannabis dispensary in Minnesota and the ideal destination for those with refined taste, higher standards, and a creative spirit. Step through our doors and onto the path of elevated quality of life. Our shelves offer healthy options, amazing flavors, and purity of ingredients. We source next-level cannabis producers to provide unmatched excellence.</p><p>Gigli is a brand that delights, inspires, and innovates. Their offerings are all natural and vegan- and gluten-free. Award-winning tastes are oh-so-tempting yet under 100 calories. We especially appreciate the combination of superfoods such as Ashwagandha and Ginseng. Ashwagandha is an evergreen shrub utilized in wellness practices for centuries and proven by way of modern studies as effective in treating stress, anxiety, and difficulty sleeping. Rich in antioxidants, Ginseng is often used to reduce inflammation, enhance immune strength, and boost mood and energy levels.</p><p>Swap out your beer, wine, or alcoholic cocktail for a Blueberry Lemonade, Raspberry Ginger Mule, Blood Orange Margarita, or Pineapple Mojito from Gigli and skip the hangover. Sample some especially yummy gummies in flavors such as Mixed Fruit, Watermelon, Peach Rings, and Sour Fruit. Indulge in velvety smooth Caramel Mocha Chocolate, Dark Chocolate, Mint Chocolate, and a variety pack that includes Funfetti and Peppermint. Sweetleaves … Where your dreams become sweeter.</p>",
    metaDescription:
      "Shop Gigli cannabis products for a premium experience. Explore our selection of high-quality products for ultimate relaxation.",
    metaTitle: "Gigli Cannabis Products | Sweetleaves",
  },
  {
    slug: "mary-jane",
    name: "Mary & Jane",
    headline: "Mary & Jane",
    category: "mary-jane",
    subheadline: "Looking for Mary & Jane in Minneapolis Metropolitan Area?",
    body: "<p>Sweetleaves offers sophisticated cannabis shopping in an ultra-high-end and elevating environment. Conveniently situated in Minneapolis Metropolitan Area, open seven days per week and staffed by educated and exceptional budtenders, we are the perfect opportunity to focus on quality of life. From health and wellness to embracing everyday joy, our selection of Mary &amp; Jane products is an ideal addition to your routine.</p><p>Mary &amp; Jane is a local, Minnesota company dedicated to control over dosing and the perfect, personalized experience. Fast-acting edibles allow for precise, easy dosing and the right amount for the beginner as well as the long-time enthusiast. Small, incremental doses fit into the daily routine for a boost of energy, enhanced focus, relaxation, or help with sleep. The Dose Discovery Kit provides step-by-step guidance for a better understanding of cannabis and control over your edible journey.</p><p>Vegan, sugar-free, and zero-calorie Sunny Melts from Mary &amp; Jane utilize kanna. Used for centuries as an herbal remedy, Kanna is a natural mood booster. A proprietary formula offers a gentle blissful and euphoric effect for a plant-powered pick-me-up. The amazing budtenders from Sweetleaves are here to sit down with you and assist in your cannabis plan and preferences. We're also available to optimize convenience with online ordering, in-store pickup, and delivery. Sweetleaves is where your dreams become sweeter.</p>",
    metaDescription:
      "Shop Mary & Jane cannabis products for a premium experience. Explore our selection of high-quality products for ultimate relaxation.",
    metaTitle: "Mary & Jane",
  },
  {
    slug: "birchs-on-the-lake",
    name: "Birch's on the Lake",
    headline: "Birch's on the Lake",
    category: "birchs-on-the-lake",
    subheadline: "Sweetleaves has Birch's on the Lake Seltzers",
    body: "<p>Birch's on the Lake was founded by a group of passionate individuals who shared a deep appreciation for the healing power of cannabis. Drawing inspiration from the serene beauty of the birch trees that line the shores of Minnesota's lakes, they set out to create a brand that would offer consumers a truly remarkable cannabis experience.</p><p>Birch's on the Lake offers THC seltzers that truly stand out by using whole, natural ingredients like real cherry juice and freshly grated ginger root. With nearly 20 years of experience in crafting carbonated beverages, Brewmaster Brennan Greene has perfected the art of sourcing the best-tasting ingredients. Each can contains 15mg of CBD, which naturally occurs alongside THC. This unique combination provides a wide range of benefits from CBD, cherry juice, and fresh ginger. Ultimately, Birch's THC seltzers offer a fun and refreshing alternative to alcohol, perfect for those looking to alter their state of mind.</p><p>We wanted to establish a place that would change the way cannabis was perceived in our local communities and provide a safe space that invites anyone and everyone—from new users to cannabis veterans—to learn and create camaraderie in a vibrant, high-end space in the North Loop of Minneapolis. Birch's on the Lake is an integral part of bringing that vision to life. Their unwavering commitment to quality, education, and community aligns perfectly with our values at Sweetleaves. Together, we strive to elevate the cannabis experience for our customers and make a positive impact in the lives of those we serve.</p>",
    metaDescription:
      "Birch's on the Lake brings healing THC edibles and drinks to Sweetleaves in Minneapolis, MN. Enjoy thoughtful, handcrafted products from Long Lake, Minnesota.",
    metaTitle: "Birch's on the Lake | Edibles & THC Drinks in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "minh-le-studio",
    name: "Minh Lê Studio",
    headline: "Minh Lê Studio",
    category: "minh-le-studio",
    subheadline: "Shop Minh Lê Studio at Sweetleaves",
    body: "<p>Visit Sweetleaves in Minneapolis to explore Minh Lê Studio's artist-crafted cannabis accessories. Where functional design meets cannabis culture.</p>",
    metaDescription:
      "Shop Minh Lê Studio cannabis accessories at Sweetleaves in Minneapolis. Artist-driven, thoughtfully designed pieces that blend craft and cannabis culture.",
  },
  {
    slug: "oliphant-brewing",
    name: "Oliphant Brewing",
    headline: "Oliphant Brewing",
    category: "oliphant-brewing",
    subheadline: "Get Oliphant Brewing at Sweetleaves",
    body: "<p>Brewer-owned and operated, Oliphant Brewing is proud to craft amazing beers and soft drinks for the weirdos of the world! Located in Somerset, Wisconsin, these Minnesota neighbors delight with unique flavors to tantalize your taste buds. Better yet? They offer vegan options! Come on into Sweetleaves today and give Oliphant Brewing a try.</p><p>You're in for a treat when you pop the top of an Oliphant Brewing can. With an incredible lineup of flavors, you will experience something truly original and maybe find your new favorite drink. How does Pineapple Wedding Cake sound? Or how about the more classic Strawberry Rhubarb Crisp? You can go for a low-dose 10mg or amp it up to a cool 25mg, but no matter which potency you prefer, Oliphant Brewing's THC-infused beverages are sure to become a staple in your refrigerator.</p><p>No matter if you're too busy to run out or if you're just comfortable lounging in your living room, you can still get your hands on some of Oliphant Brewing's fabulous beverages. Sweetleaves is here to help! Just put your order in online, and we'll deliver your Oliphant Brewing order directly to your home anywhere in the Minneapolis metropolitan area. You'll be enjoying a crisp, refreshing drink in no time.</p>",
    metaDescription:
      "Try Oliphant Brewing THC drinks from Sweetleaves in Minneapolis, MN. Bold, creative beverages crafted by Wisconsin brewers, perfect for adventurous cannabis drinkers.",
    metaTitle: "Oliphant Brewing | THC Drinks in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "session-goods",
    name: "Session Goods",
    headline: "Session Goods",
    category: "session-goods",
    subheadline: "Shop Session Goods at Sweetleaves",
    body: "<p>Visit Sweetleaves in Minneapolis to shop Session Goods cannabis accessories. Modern, minimal design meets functional engineering — built for a better session.</p>",
    metaDescription:
      "Shop Session Goods cannabis accessories at Sweetleaves in Minneapolis. Beautifully engineered, easy-to-clean pieces designed to elevate every session.",
  },
  {
    slug: "wild-state-cider-birdie",
    name: "Wild State Cider / Birdie",
    headline: "Wild State Cider/Birdie",
    category: "wild-state-cider-birdie",
    subheadline: "Get Birdie at Sweetleaves",
    body: "<p>Wild State Cider is a Minnesota-based company that has been crafting exceptional ciders since 2019. With a passion for innovation and a commitment to using only the finest ingredients, Wild State Cider has quickly become a beloved brand among cider enthusiasts. In August of 2023, when Governor Walz signed recreational cannabis into law, the team at Wild State Cider saw an opportunity to expand their offerings and create a unique cannabis experience for their customers.</p><p>The Birdie line of non-alcoholic, cannabis-infused ciders is the result of Wild State Cider's dedication to quality and creativity. Each cider is carefully crafted using a blend of fresh, locally-sourced apples and high-quality Delta-9 hemp extract. The result is a refreshing and flavorful beverage that offers a perfect balance of sweet and tart notes, with a subtle cannabis twist. Offering flavors like Tropical Green Tea, Wild Berry Lemonade, Blood Orange Hibiscus, and Moscow Mule, these drinks are the pinnacle of a delightful sipping experience.</p><p>There is nothing quite like a Wild State Cider brew. As a company founded on the purest form of the term &ldquo;natural&rdquo;, you can expect that every drink is chock-full of only the best. With only easy-to-pronounce ingredients like sparkling water and cane sugar, you'll know you're drinking 100% fruit without the addition of concentrates or artificial flavors. Wild State Cider prioritizes using Minnesota-grown products in their beverages, supporting local business and maintaining the quality of product that is normally lost in cross-country shipping.</p>",
    metaDescription:
      "Savor Wild State Cider's Birdie THC drinks from Sweetleaves in Minneapolis, MN. Made in Minnesota, these drinks offer a refreshing, flavorful cannabis experience.",
    metaTitle: "Birdie by Wild State Cider | THC Drinks in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "wyld",
    name: "WYLD",
    dutchieParams: { "dtche[path]": "brands/wyld" },
    headline: "WYLD",
    category: "wyld",
    subheadline: "SWEETLEAVES HAS WYLD EDIBLES",
    body: "<p>Focusing on innovative edibles and the science of cannabinoids, WYLD is a people-first brand that also places a dedicated focus on the planet. Their attention to environmental sustainability and social justice, along with their delicious line of edible products, will leave you feeling great!</p><p>At Sweetleaves, we're committed to providing our customers with the best possible cannabis experience. That's why we're proud to feature WYLD products in our dispensary. We believe that everyone deserves access to safe, high-quality cannabis products, and we're dedicated to making that a reality in the Minneapolis Metropolitan Area. WYLD's success is built upon flavors inspired by nature, superior ingredients, precise dosing, and one key goal: creating the best-tasting edibles worldwide. The brand has earned a reputation for delivering reliable and consistent cannabis experiences that customers trust. Beyond flavor, the gummies are developed and constantly refined by a team of food scientists and quality experts, ensuring each package of WYLD upholds the highest standards.</p><p>WYLD was established in 2016 as a small operation by three college friends in Central Oregon with a mission to craft premium cannabis edibles featuring real fruit and real flavors. The company's journey from modest origins to becoming a global leader in the cannabis industry has been fueled by a dedication to quality, operational excellence, and strong collaborations with retailers and budtenders. WYLD has maintained its independence and progressive approach to growth, ensuring the preservation of high product standards and ethical business practices. The company remains committed to its founding principles, acting with integrity and passion.</p>",
    metaDescription:
      "Shop WYLD edibles at Sweetleaves in Minneapolis, MN. Crafted with innovation and a commitment to sustainability, these edibles bring the science of cannabinoids to life.",
    metaTitle: "WYLD | Edibles in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "rythm",
    name: "RYTHM",
    dutchieParams: { "dtche[path]": "brands/rythm" },
    headline: "RYTHM",
    category: "rythm",
    subheadline: "The Art of RYTHM Flower",
    body: "<p>RYTHM was created for those who see cannabis as part of their creative flow. Built on a foundation of artistry and self-expression, RYTHM cultivates flower that inspires, calms, and connects. Each strain is grown with care and precision to deliver a consistent, elevated experience that helps you tune in to your ideal state of mind.</p><p>RYTHM flower represents the perfect balance of science and artistry. Each cultivar is grown with care, emphasizing terpene richness, smooth flavor, and reliable potency. From energizing sativas to deeply relaxing indicas, RYTHM's lineup delivers premium quality and distinct character in every bud. Known nationwide for consistency and craftsmanship, RYTHM flower is now available in Minnesota, bringing a trusted name in cannabis to local consumers.</p><p>We're proud to offer RYTHM flower as part of our mission to elevate cannabis culture in Minnesota. Like us, RYTHM celebrates the connection between people, creativity, and community. Visit our North Loop dispensary in Minneapolis to explore RYTHM's carefully curated strains in a space where both new and experienced consumers can discover their perfect rhythm.</p>",
    metaDescription:
      "Discover RYTHM flower at Sweetleaves in Minneapolis. Premium strains crafted to inspire, relax, and connect for every cannabis enthusiast.",
    metaTitle: "RYTHM | Flower in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "dogwalkers",
    name: "Dogwalkers",
    dutchieParams: { "dtche[path]": "brands/dogwalkers" },
    headline: "Dogwalkers",
    category: "dogwalkers",
    subheadline: "Pre-Rolls With Purpose",
    body: "<p>Dogwalkers was created with a simple idea in mind: enjoying life one walk at a time. Inspired by the founder's dog, Bailey, the brand focuses on crafting premium pre-rolls designed to elevate everyday moments. Each purchase supports local animal rescue organizations, allowing Dogwalkers to give back while delivering dependable, high-quality cannabis.</p><p>Dogwalkers pre-rolls are made from high-quality flower and rolled with care to ensure smooth, consistent sessions. They offer convenient sizes for any occasion, from quick Mini Dog moments to full Big Dog experiences, along with infused Show Dog options for stronger potency. Whether you're looking for something mellow or more robust, Dogwalkers provides reliable effects paired with a mission that supports animal rescue efforts across the communities they serve.</p><p>Sweetleaves is proud to offer Dogwalkers because the brand reflects our dedication to carrying premium cannabis while supporting positive community impact. Visit our North Loop dispensary in Minneapolis to get Dogwalkers pre-rolls and enjoy a thoughtfully crafted cannabis experience that also helps support animals in need.</p>",
    metaDescription:
      "Find Dogwalkers at Sweetleaves in Minneapolis. Quality pre-rolls crafted from premium flower that helps support animal rescue.",
    metaTitle: "Dogwalkers | Pre-Rolls in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "good-green",
    name: "Good Green",
    dutchieParams: { "dtche[path]": "brands/good-green" },
    headline: "Good Green",
    category: "good-green",
    subheadline: "Flower with a Mission",
    body: "<p>Good Green is more than just a product. Good Green is dedicated to supporting communities affected by the War on Drugs through education, employment, and expungement initiatives. Each strain is carefully grown to deliver premium flower with smooth flavor and reliable effects. With every purchase, you support a broader mission of social responsibility, making Good Green a brand you can feel good about.</p><p>Good Green flower is cultivated to highlight rich terpene profiles, consistent potency, and approachable effects. Their selection includes uplifting sativas and calming indicas, giving both new and experienced users a reliable experience. Good Green's combination of high-quality flower and mission-driven focus allows consumers to enjoy premium cannabis while supporting meaningful community initiatives.</p><p>Sweetleaves is proud to carry Good Green because it reflects our commitment to offering top-shelf flower while supporting meaningful community initiatives. This brand's focus on quality, consistency, and social impact aligns perfectly with our values. Visit our North Loop dispensary in Minneapolis to explore Good Green flower and enjoy a premium cannabis experience that also contributes to positive change in the communities we serve.</p>",
    metaDescription:
      "Explore Good Green flower at Sweetleaves in Minneapolis. Premium cannabis with reliable quality and a mission to support communities in need.",
    metaTitle: "Good Green | Flower in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "grasslandz",
    name: "Grasslandz",
    dutchieParams: { "dtche[path]": "brands/grasslandz" },
    headline: "Grasslandz",
    category: "grasslandz",
    subheadline: "Cartridges Crafted with Intention",
    body: "<p>Grasslandz was created with a deep respect for the land, the plant, and the communities connected to both. Rooted in regenerative, sun-grown cultivation practices, the brand focuses on producing cannabis that reflects care, balance, and intention. Every harvest is grown to highlight the plant's natural character while honoring sustainability and stewardship. Grasslandz delivers a grounded, authentic cannabis experience built on quality and purpose.</p><p>Grasslandz vape cartridges are made with the same care and attention as their cultivation practices, focusing on clean flavor, smooth vapor, and consistent effects. Each cartridge is thoughtfully produced to preserve terpene character and deliver a balanced, reliable experience. This quality-first approach creates vapes that feel approachable and enjoyable for both seasoned consumers and those new to cannabis.</p><p>Sweetleaves is proud to carry Grasslandz because the brand delivers high-quality vape cartridges with consistent performance and flavor. Their thoughtful production practices reflect the standards we value in the brands we offer. Visit our flagship North Loop dispensary in Minneapolis to get your Grasslandz cartridges and enjoy a smooth, carefully crafted cannabis experience.</p>",
    metaDescription:
      "Explore Grasslandz cartridges at Sweetleaves in Minneapolis. Sun-grown, regenerative cannabis crafted with care, quality, and intention.",
    metaTitle: "Grasslandz | Vapes in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "nebula",
    name: "Nebula",
    dutchieParams: { "dtche[path]": "brands/nebula" },
    headline: "Nebula",
    category: "nebula",
    subheadline: "Nebula Cannabis Made Simple and Dependable",
    body: "<p>Nebula brings a modern approach to cannabis, blending creativity and quality to deliver smooth, reliable effects. Rooted in Minnesota, Nebula is focused on making cannabis reliable for consumers who want a convenient and satisfying experience.</p><p>Nebula cartridges and edibles are crafted to provide smooth, reliable effects and distinct flavor profiles. Each product is designed with quality and consistency in mind, making them a dependable choice for everyday use or social moments. Nebula offers cannabis that's approachable, enjoyable, and suited for both new and experienced consumers.</p><p>Sweetleaves carries Nebula for their high-quality cartridges and edibles, delivering smooth effects, bold flavor, and consistent performance. With reliable products and a strong local presence, Nebula is a great choice for everyday use or on-the-go enjoyment. Visit our flagship North Loop dispensary in Minneapolis to explore Nebula vapes and edibles.</p>",
    metaDescription:
      "Explore Nebula cartridges and edibles at Sweetleaves in Minneapolis. Enjoy flavorful, and consistent cannabis experiences with Nebula.",
    metaTitle: "Nebula | Vapes & Edibles in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "lakeside-cannabis-co",
    name: "Lakeside Cannabis Co.",
    dutchieParams: { "dtche[path]": "brands/lakeside-cannabis-co" },
    headline: "Lakeside Cannabis Co.",
    category: "lakeside-cannabis-co",
    subheadline: "Cannabis for Easygoing Moments",
    body: "<p>Lakeside Cannabis Co. was created to complement the moments that matter most, from laid-back afternoons to nights spent unwinding with friends. Inspired by lake life and outdoor leisure, Lakeside Cannabis Co. focuses on approachable, high-quality cannabis designed for easy enjoyment.</p><p>Lakeside Cannabis Co. cartridges and disposable vapes are crafted to deliver smooth flavor, dependable potency, and balanced effects that fit a wide range of occasions. Whether you're looking to unwind, socialize, or enjoy the moment, their vapes are designed to be approachable and easy to use. This relaxed approach makes Lakeside a reliable choice for both casual consumers and experienced cannabis users.</p><p>Lakeside Cannabis Co. offers cartridges and disposables made for enjoyable, everyday experiences, and Sweetleaves is proud to carry their products. With consistent effects, approachable profiles, and a focus on quality, Lakeside fits naturally into our curated vape selection. Stop by our flagship North Loop dispensary in Minneapolis to explore Lakeside Cannabis Co. vapes and enjoy cannabis designed for relaxed, memorable moments.</p>",
    metaDescription:
      "Explore Lakeside Cannabis Co. cartridges and disposables at Sweetleaves in Minneapolis. Easygoing, high-quality vapes crafted for relaxed moments.",
    metaTitle: "Lakeside Cannabis Co. | Vapes in Minneapolis MN | Sweetleaves",
  },
];
