import type { CatalogEntry } from "./catalog";

export const brands: CatalogEntry[] = [
  {
    slug: "sweetleaves",
    name: "Sweetleaves",
    dutchieParams: { "dtche[path]": "brands/sweetleaves" },
    headline: "Sweetleaves",
    category: "sweetleaves",
    subheadline: "Shop Sweetleaves at Sweetleaves",
    body: "<p>We are committed to creating a high-end and vibrant space focused on education, community, and inclusivity. Sweetleaves is where your dreams become sweeter.</p>",
    metaDescription:
      "Shop Sweetleaves cannabis products for Minneapolis, MN. Contact us today for more info about our cannabis products!",
    metaTitle: "Sweetleaves Products | Sweetleaves",
  },
  {
    slug: "blncd",
    name: "BLNCD",
    headline: "BLNCD",
    category: "blncd",
    subheadline: "Shop BLNCD at Sweetleaves",
    body: "<p>Discover BLNCD's clean, plant-based wellness products at Sweetleaves in Minneapolis. Ethically sourced, small-batch, and crafted with care from farm to table.</p>",
    metaDescription:
      "Shop BLNCD Naturals at Sweetleaves in Minneapolis. Women-owned, USDA Organic, small-batch cannabis wellness and skincare made in Northeast Minneapolis.",
  },
  {
    slug: "cann",
    name: "CANN",
    headline: "CANN",
    category: "cann",
    subheadline: "Shop CANN at Sweetleaves",
    body: "<p>Sweetleaves is where dreams become sweeter. Stop in or order online and get CANN delivered anywhere in the Minneapolis metropolitan area.</p>",
    metaDescription:
      "Shop CANN cannabis beverages at Sweetleaves in Minneapolis. Bubbly, low-dose social drinks — a healthier alternative to alcohol, delivered in the Minneapolis metro.",
  },
  {
    slug: "raw",
    name: "RAW",
    headline: "RAW",
    category: "raw",
    subheadline: "Shop RAW at Sweetleaves",
    body: "<p>Find RAW rolling papers, cones, and accessories at Sweetleaves in Minneapolis. Quality unbleached, plant-based papers for every kind of smoker.</p>",
    metaDescription:
      "Shop RAW rolling papers and cones at Sweetleaves in Minneapolis. Unbleached, plant-based papers, cones, and accessories for every style of smoker.",
  },
  {
    slug: "nowadays",
    name: "Nowadays",
    headline: "Nowadays",
    category: "nowadays",
    subheadline: "Shop Nowadays at Sweetleaves",
    body: "<p>Spend some time with us or let us accommodate your hectic schedule with online ordering, in-store pickup, or delivery. Sweetleaves is where your dreams become sweeter.</p>",
    metaDescription:
      "Shop Nowadays cannabis products for a premium experience. Explore our selection of high-quality products for ultimate relaxation.",
    metaTitle: "Nowadays Cannabis Products | Sweetleaves",
  },
  {
    slug: "gigli",
    name: "Gigli",
    headline: "Gigli",
    category: "gigli",
    subheadline: "Shop Gigli at Sweetleaves",
    body: "<p>Sweetleaves … Where your dreams become sweeter. Discover Gigli's full lineup of all-natural, vegan, and gluten-free cannabis products in our Minneapolis dispensary.</p>",
    metaDescription:
      "Shop Gigli cannabis products for a premium experience. Explore our selection of high-quality products for ultimate relaxation.",
    metaTitle: "Gigli Cannabis Products | Sweetleaves",
  },
  {
    slug: "mary-jane",
    name: "Mary & Jane",
    headline: "Mary & Jane",
    category: "mary-jane",
    subheadline: "Shop Mary & Jane at Sweetleaves",
    body: "<p>The amazing budtenders from Sweetleaves are here to sit down with you and assist in your cannabis plan and preferences. We're also available to optimize convenience with online ordering, in-store pickup, and delivery.</p>",
    metaDescription:
      "Shop Mary & Jane cannabis products for a premium experience. Explore our selection of high-quality products for ultimate relaxation.",
    metaTitle: "Mary & Jane",
  },
  {
    slug: "birchs-on-the-lake",
    name: "Birch's on the Lake",
    headline: "Birch's on the Lake",
    category: "birchs-on-the-lake",
    subheadline: "Shop Birch's on the Lake at Sweetleaves",
    body: "<p>Discover Birch's on the Lake THC seltzers at Sweetleaves in Minneapolis. Naturally crafted, community-focused, and crafted by a brewmaster with nearly 20 years of experience.</p>",
    metaDescription:
      "Birch's on the Lake brings healing THC edibles and drinks to Sweetleaves in Minneapolis, MN. Enjoy thoughtful, handcrafted products from Long Lake, Minnesota.",
    metaTitle: "Birch's on the Lake | Edibles & THC Drinks in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "clrty",
    name: "Clr!ty",
    headline: "Clr!ty",
    category: "clrty",
    subheadline: "Shop Clr!ty at Sweetleaves",
    body: "<p>Stop in to Sweetleaves in Minneapolis to explore Clr!ty's full lineup of fast-acting THC seltzers, shots, mixers, and cold brew coffees.</p>",
    metaDescription:
      "Shop Clr!ty THC beverages at Sweetleaves in Minneapolis. Fast-acting hemp-derived THC seltzers, shots, mixers, and cold brews in 5mg and 10mg potencies.",
  },
  {
    slug: "find-wunder",
    name: "Find Wunder",
    headline: "Find Wunder",
    category: "find-wunder",
    subheadline: "Shop Find Wunder at Sweetleaves",
    body: "<p>Find Wunder at Sweetleaves in Minneapolis and discover why millions of cans have been sold. A better alternative to alcohol, crafted by passionate beverage enthusiasts.</p>",
    metaDescription:
      "Shop Find Wunder THC beverages at Sweetleaves in Minneapolis. One of the top THC beverage brands in the country — a genuine, better alternative to alcohol.",
  },
  {
    slug: "minh-le-studio",
    name: "Minh Lê Studio",
    headline: "Minh Lê Studio",
    category: "minh-le-studio",
    subheadline: "Shop Minh Lê Studio at Sweetleaves",
    body: "<p>Visit Sweetleaves in Minneapolis to explore Minh Lê Studio's artist-crafted cannabis accessories. Where functional design meets cannabis culture.</p>",
    metaDescription:
      "Shop Minh Lê Studio cannabis accessories at Sweetleaves in Minneapolis. Artist-driven, thoughtfully designed pieces that blend craft and cannabis culture.",
  },
  {
    slug: "oliphant-brewing",
    name: "Oliphant Brewing",
    headline: "Oliphant Brewing",
    category: "oliphant-brewing",
    subheadline: "Shop Oliphant Brewing at Sweetleaves",
    body: "<p>Stop in or order online to discover Oliphant Brewing's THC-infused beverages at Sweetleaves in Minneapolis. Craft, creativity, and bold flavors — for the weirdos of the world.</p>",
    metaDescription:
      "Try Oliphant Brewing THC drinks from Sweetleaves in Minneapolis, MN. Bold, creative beverages crafted by Wisconsin brewers, perfect for adventurous cannabis drinkers.",
    metaTitle: "Oliphant Brewing | THC Drinks in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "ongrok",
    name: "ONGROK",
    headline: "ONGROK",
    category: "ongrok",
    subheadline: "Shop ONGROK at Sweetleaves",
    body: "<p>Find ONGROK cannabis accessories at Sweetleaves in Minneapolis. Premium materials, modern design, and a performance guarantee on every item.</p>",
    metaDescription:
      "Shop ONGROK cannabis accessories at Sweetleaves in Minneapolis. North American-designed, premium hardwood and aluminum accessories with a performance guarantee.",
  },
  {
    slug: "session-goods",
    name: "Session Goods",
    headline: "Session Goods",
    category: "session-goods",
    subheadline: "Shop Session Goods at Sweetleaves",
    body: "<p>Visit Sweetleaves in Minneapolis to shop Session Goods cannabis accessories. Modern, minimal design meets functional engineering — built for a better session.</p>",
    metaDescription:
      "Shop Session Goods cannabis accessories at Sweetleaves in Minneapolis. Beautifully engineered, easy-to-clean pieces designed to elevate every session.",
  },
  {
    slug: "studio-tbd",
    name: "Studio TBD",
    headline: "Studio TBD",
    category: "studio-tbd",
    subheadline: "Shop Studio TBD at Sweetleaves",
    body: "<p>Discover Studio TBD vapes, pre-rolls, and edibles at Sweetleaves in Minneapolis. A creative collective dedicated to elevating the cannabis experience.</p>",
    metaDescription:
      "Shop Studio TBD cannabis vapes, pre-rolls, and edibles at Sweetleaves in Minneapolis. NYC-based creative collective bringing thoughtful design to cannabis.",
  },
  {
    slug: "wild-state-cider-birdie",
    name: "Wild State Cider / Birdie",
    headline: "Wild State Cider / Birdie",
    category: "wild-state-cider-birdie",
    subheadline: "Shop Wild State Cider / Birdie at Sweetleaves",
    body: "<p>Find Wild State Cider's Birdie line at Sweetleaves in Minneapolis. Minnesota-grown, non-alcoholic, cannabis-infused ciders crafted with real fruit and Delta-9 hemp extract.</p>",
    metaDescription:
      "Savor Wild State Cider's Birdie THC drinks from Sweetleaves in Minneapolis, MN. Made in Minnesota, these drinks offer a refreshing, flavorful cannabis experience.",
    metaTitle: "Birdie by Wild State Cider | THC Drinks in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "wyld",
    name: "WYLD",
    dutchieParams: { "dtche[path]": "brands/wyld" },
    headline: "WYLD",
    category: "wyld",
    subheadline: "Shop WYLD at Sweetleaves",
    body: "<p>Shop WYLD cannabis edibles at Sweetleaves in Minneapolis. Nature-inspired flavors, real fruit, and precise dosing — crafted by one of the world's leading cannabis edible brands.</p>",
    metaDescription:
      "Shop WYLD edibles at Sweetleaves in Minneapolis, MN. Crafted with innovation and a commitment to sustainability, these edibles bring the science of cannabinoids to life.",
    metaTitle: "WYLD | Edibles in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "rythm",
    name: "RYTHM",
    dutchieParams: { "dtche[path]": "brands/rythm" },
    headline: "RYTHM",
    category: "rythm",
    subheadline: "Shop RYTHM at Sweetleaves",
    body: "<p>Explore RYTHM flower strains at Sweetleaves in Minneapolis. Consistent quality, terpene-rich cultivars, and a brand built on artistry and self-expression.</p>",
    metaDescription:
      "Discover RYTHM flower at Sweetleaves in Minneapolis. Premium strains crafted to inspire, relax, and connect for every cannabis enthusiast.",
    metaTitle: "RYTHM | Flower in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "dogwalkers",
    name: "Dogwalkers",
    dutchieParams: { "dtche[path]": "brands/dogwalkers" },
    headline: "Dogwalkers",
    category: "dogwalkers",
    subheadline: "Shop Dogwalkers at Sweetleaves",
    body: "<p>Pick up Dogwalkers pre-rolls at Sweetleaves in Minneapolis. Premium cannabis, smooth sessions, and a mission that supports local animal rescue organizations.</p>",
    metaDescription:
      "Find Dogwalkers at Sweetleaves in Minneapolis. Quality pre-rolls crafted from premium flower that helps support animal rescue.",
    metaTitle: "Dogwalkers | Pre-Rolls in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "good-green",
    name: "Good Green",
    dutchieParams: { "dtche[path]": "brands/good-green" },
    headline: "Good Green",
    category: "good-green",
    subheadline: "Shop Good Green at Sweetleaves",
    body: "<p>Visit our North Loop dispensary in Minneapolis to explore Good Green flower and enjoy a premium cannabis experience that also contributes to positive change in the communities we serve.</p>",
    metaDescription:
      "Explore Good Green flower at Sweetleaves in Minneapolis. Premium cannabis with reliable quality and a mission to support communities in need.",
    metaTitle: "Good Green | Flower in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "grasslandz",
    name: "Grasslandz",
    dutchieParams: { "dtche[path]": "brands/grasslandz" },
    headline: "Grasslandz",
    category: "grasslandz",
    subheadline: "Shop Grasslandz at Sweetleaves",
    body: "<p>Find Grasslandz vape cartridges at Sweetleaves in Minneapolis. Sun-grown, regeneratively cultivated cannabis — clean flavor, smooth vapor, consistent effects.</p>",
    metaDescription:
      "Explore Grasslandz cartridges at Sweetleaves in Minneapolis. Sun-grown, regenerative cannabis crafted with care, quality, and intention.",
    metaTitle: "Grasslandz | Vapes in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "nebula",
    name: "Nebula",
    dutchieParams: { "dtche[path]": "brands/nebula" },
    headline: "Nebula",
    category: "nebula",
    subheadline: "Shop Nebula at Sweetleaves",
    body: "<p>Discover Nebula cannabis cartridges and edibles at Sweetleaves in Minneapolis. Modern, reliable, and consistently smooth — cannabis made simple.</p>",
    metaDescription:
      "Explore Nebula cartridges and edibles at Sweetleaves in Minneapolis. Enjoy flavorful, and consistent cannabis experiences with Nebula.",
    metaTitle: "Nebula | Vapes & Edibles in Minneapolis MN | Sweetleaves",
  },
  {
    slug: "lakeside-cannabis-co",
    name: "Lakeside Cannabis Co.",
    dutchieParams: { "dtche[path]": "brands/lakeside-cannabis-co" },
    headline: "Lakeside Cannabis Co.",
    category: "lakeside-cannabis-co",
    subheadline: "Shop Lakeside Cannabis Co. at Sweetleaves",
    body: "<p>Stop by our flagship North Loop dispensary in Minneapolis to explore Lakeside Cannabis Co. vapes and enjoy cannabis designed for relaxed, memorable moments.</p>",
    metaDescription:
      "Explore Lakeside Cannabis Co. cartridges and disposables at Sweetleaves in Minneapolis. Easygoing, high-quality vapes crafted for relaxed moments.",
    metaTitle: "Lakeside Cannabis Co. | Vapes in Minneapolis MN | Sweetleaves",
  },
];
